name: neiman_inventory
version: 1.0.0+1
publish_to: none
description: A new Flutter project.
environment: 
  sdk: '>=2.16.2 <3.0.0'

dependencies: 
  cupertino_icons: ^1.0.2
  get: 4.6.1
  get_storage: 2.0.3
  http: 0.13.4
  connectivity_plus: 2.3.0
  intl: 0.17.0
  google_fonts: 2.3.1
  internet_connection_checker: 0.0.1+3
  flutter: 
    sdk: flutter

dev_dependencies: 
  flutter_lints: ^1.0.0
  flutter_test: 
    sdk: flutter

flutter: 
  uses-material-design: true

