name: neiman_inventory
version: 1.0.0+1
publish_to: none
description: A new Flutter project.
environment: 
  sdk: '>=2.16.2 <3.0.0'

dependencies: 
  cupertino_icons: ^1.0.2
  get: 4.6.1
  get_storage: 2.0.3
  http: 0.13.4
  connectivity_plus: 2.3.0
  intl: 0.17.0
  google_fonts: 2.3.1
  internet_connection_checker: 0.0.1+3
  firebase_analytics: ^9.1.6
  firebase_crashlytics: ^2.6.3
  firebase_core: any
  cached_network_image: 3.2.0
  flutter: 
    sdk: flutter

dev_dependencies: 
  flutter_lints: ^1.0.0
  flutter_launcher_icons: ^0.9.2
  build_runner: ^2.1.0
  flutter_test: 
    sdk: flutter


flutter_icons:
  image_path: assets/images/app_logo.jpg
  android: true
  ios: true


flutter:
  assets:
    - assets/
    - assets/images/
  uses-material-design: true

